[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
    description = "my personal collection of unfiltered & unedited ChatGPT responses i've found funny " 
  [params.theme_config]
    appearance = "light"
    back_home_text = ".."
    date_format = ""
    show_description = true
  [[params.links.developer]]
      url = "mailto:foo@bar.com"
      name = "Mail me"
      weight = 4